import { useState, useCallback } from 'react';
import { Octokit } from '@octokit/rest';

export function useGitHub() {
  const [token, setToken] = useState(localStorage.getItem('githubToken') || '');
  const [repo, setRepo] = useState(localStorage.getItem('githubRepo') || '');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  const octokit = useCallback(() => {
    if (!token) throw new Error('GitHub token required');
    return new Octokit({ auth: token });
  }, [token]);

  const connect = useCallback((newToken, newRepo) => {
    localStorage.setItem('githubToken', newToken);
    localStorage.setItem('githubRepo', newRepo);
    setToken(newToken);
    setRepo(newRepo);
    setError('');
  }, []);

  const exportReport = useCallback(async (reportData, candidateName = 'report') => {
    if (!token || !repo) throw new Error('Connect GitHub first');
    setLoading(true);
    setError('');

    try {
      const { overallScore, topStrengths, criticalImprovements, scores, verdict } = reportData;
      const date = new Date().toISOString().split('T')[0];
      const fileName = `resume-reports/${candidateName}-${overallScore}-${date}.md`;

      const content = `# AI Resume Analysis Report\n\n` +
        `**Score**: ${overallScore}%\n` +
        `**Candidate**: ${candidateName}\n` +
        `**Date**: ${date}\n\n` +
        `## Top Strengths\n${topStrengths?.map(s => `- ${s}`).join('\n') || 'N/A'}\n\n` +
        `## Critical Improvements\n${criticalImprovements?.map(i => `- ${i}`).join('\n') || 'N/A'}\n\n` +
        `## Scores\n${Object.entries(scores || {}).map(([k,v]) => `**${k}**: ${v}`).join('\n')}\n\n` +
        `## Verdict\n${verdict}\n\n` +
        `---\nGenerated by ResumeAI`;

      const { data: { sha } } = await octokit().rest.repos.getContent({
        owner: repo.split('/')[0],
        repo: repo.split('/')[1],
        path: fileName,
      }).catch(() => ({ data: { sha: null } }));

      await octokit().rest.repos.createOrUpdateFileContents({
        owner: repo.split('/')[0],
        repo: repo.split('/')[1],
        path: fileName,
        message: `Add resume report: ${candidateName} (${overallScore}%)`,
        content: btoa(content),
        sha,
      });

      return { success: true, file: fileName };
    } catch (err) {
      setError(err.message);
      throw err;
    } finally {
      setLoading(false);
    }
  }, [token, repo]);

  const disconnect = useCallback(() => {
    localStorage.removeItem('githubToken');
    localStorage.removeItem('githubRepo');
    setToken('');
    setRepo('');
  }, []);

  return {
    token, repo, loading, error,
    connect, exportReport, disconnect,
    isConnected: !!token && !!repo
  };
}










